In [1]:
import pandas as pd

df = pd.read_csv("../data/Ridership.csv")

print("First 5 rows:")
display(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nBasic statistics:")
display(df.describe())

First 5 rows:

  service_date day_type     bus  rail_boardings  total_rides
0     1/1/2001        U  297192          126455       423647
1     1/2/2001        W  780827          501952      1282779
2     1/3/2001        W  824923          536432      1361355
3     1/4/2001        W  870021          550011      1420032
4     1/5/2001        W  890426          557917      1448343

Dataset shape:
(7701, 5)

Column names:
['service_date', 'day_type', 'bus', 'rail_boardings', 'total_rides']

Data types:
service_date        str
day_type            str
bus               int64
rail_boardings    int64
total_rides       int64
dtype: object

Missing values:
service_date      0
day_type          0
bus               0
rail_boardings    0
total_rides       0
dtype: int64

Basic statistics:

                bus  rail_boardings   total_rides
count  7.701000e+03    7.701000e+03  7.701000e+03
mean   7.527179e+05    5.413338e+05  1.294052e+06
std    2.622677e+05    2.053125e+05  4.522545e+05
min    8.078300e+04    2.354400e+04  1.100470e+05
25%    5.069290e+05    3.556960e+05  8.865430e+05
50%    8.346400e+05    6.093250e+05  1.522615e+06
75%    9.760220e+05    7.103610e+05  1.649729e+06
max    1.211992e+06    1.146516e+06  2.049519e+06

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7701 entries, 0 to 7700
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    7701 non-null   str
 1   day_type        7701 non-null   str
 2   bus             7701 non-null   int64
 3   rail_boardings  7701 non-null   int64
 4   total_rides     7701 non-null   int64
dtypes: int64(3), str(2)
memory usage: 300.9 KB

In [3]:
df.describe()

                bus  rail_boardings   total_rides
count  7.701000e+03    7.701000e+03  7.701000e+03
mean   7.527179e+05    5.413338e+05  1.294052e+06
std    2.622677e+05    2.053125e+05  4.522545e+05
min    8.078300e+04    2.354400e+04  1.100470e+05
25%    5.069290e+05    3.556960e+05  8.865430e+05
50%    8.346400e+05    6.093250e+05  1.522615e+06
75%    9.760220e+05    7.103610e+05  1.649729e+06
max    1.211992e+06    1.146516e+06  2.049519e+06

In [4]:
df["service_date"] = pd.to_datetime(df["service_date"])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7701 entries, 0 to 7700
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    7701 non-null   datetime64[us]
 1   day_type        7701 non-null   str
 2   bus             7701 non-null   int64
 3   rail_boardings  7701 non-null   int64
 4   total_rides     7701 non-null   int64
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 300.9 KB

In [6]:
df["service_date"].duplicated().sum()

np.int64(62)

In [7]:
df[df["service_date"].duplicated(keep=False)].sort_values("service_date").head(20)

     service_date day_type      bus  rail_boardings  total_rides
3926   2011-10-01        A   701783          480889      1182672
3957   2011-10-01        A   701783          480889      1182672
3927   2011-10-02        U   486409          344520       830929
3958   2011-10-02        U   486409          344520       830929
3928   2011-10-03        W  1091676          751034      1842710
3959   2011-10-03        W  1091676          751034      1842710
3929   2011-10-04        W  1090878          767029      1857907
3960   2011-10-04        W  1090878          767029      1857907
3930   2011-10-05        W  1083300          774142      1857442
3961   2011-10-05        W  1083300          774142      1857442
3962   2011-10-06        W  1076741          783363      1860104
3931   2011-10-06        W  1076741          783363      1860104
3932   2011-10-07        W  1074577          783590      1858167
3963   2011-10-07        W  1074577          783590      1858167
3964   2011-10-08        A   692368          523113      1215481
3933   2011-10-08        A   692368          523113      1215481
3934   2011-10-09        U   463310          519453       982763
3965   2011-10-09        U   463310          519453       982763
3935   2011-10-10        W   857528          669173      1526701
3966   2011-10-10        W   857528          669173      1526701

In [8]:
df = df.drop_duplicates()

In [9]:
df["service_date"].duplicated().sum()

np.int64(0)

In [10]:
df["service_date"].is_monotonic_increasing

False

In [11]:
df = df.sort_values("service_date").reset_index(drop=True)

In [12]:
df["service_date"].is_monotonic_increasing

True

In [13]:
df["service_date"].diff().value_counts().head()

service_date
1 days    7638
Name: count, dtype: int64

In [14]:
df["service_date"].diff().value_counts().sort_index()

service_date
1 days    7638
Name: count, dtype: int64

In [15]:
df.to_csv("../data/ridership_cleaned.csv", index=False)